language: python
sudo: required
services:
  - docker
python:
  - 3.6
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.21.1
    - BROKER_USER=user
    - BROKER_PASSWORD=password
    - REPOSITORY_DIR=/data/repository
    - WORKING_DIR=/data/workspace
    - STAGING_DIR=/data/staging
    - CONFIG_DIR=/config
    - UID=2000
    - DEFAULT_TEST_TIMEOUT=30000
    - JOURNAL_TEST_TIMEOUT=180000
    - OJS_SERVER=ojs
    - OJS_PATH=ojs
    - OJS_PORT=80
    - OJS_AUTH_KEY=YWRtaW4=:cGFzc3dvcmQ=
    - JOB_DB_URL=job-db
    - JOB_DB_PORT=27017
    - JOB_DB_NAME=job_database
    - BACKEND_URI=http://localhost:5000
    - ZENON_URI=https://zenon.dainst.org/api/v1
    - OJS_URI=http://localhost:4444/ojs/plugins/generic/ojs-cilantro-plugin/api
    - BACKEND_URI_TEST=http://service:5000
    - ZENON_URI_TEST=https://zenon.dainst.org/api/v1
    - OJS_URI_TEST=http://ojs:80/ojs/plugins/generic/ojs-cilantro-plugin/api
    - OLD_JOBS_THRESHOLD_DAYS=7
    - ARACHNE_DB_HOST=arachne-db
    - ARACHNE_DB_NAME=arachne
    - ARACHNE_DB_USER=root
    - ARACHNE_DB_PASSWORD=password
    - ARCHAEOCLOUD_PATH=/archaeocloud_test_dir
before_install:
  - cp config/users.yml-default config/users.yml
  - sudo apt-get install -y python3-dev libpoppler-cpp-dev
  - pip3 install -r doc/requirements.txt
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - mkdir data
  - mkdir data/staging
  - mkdir data/staging/test_user
  - mkdir data/repository
  - mkdir data/workspace
  - docker-compose pull && docker-compose up -d
script:
  - sleep 20 && bash frontend/test/exec_frontend_test.sh
  - bash test/exec_docker_test.sh
  - bash doc/build-doc.sh
  - docker-compose logs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/_build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
