version: '3.5'

services:

  db:
    volumes:
      - redis-data:/data

  service:
    volumes:
      - data:/data
      - /opt/cilantro/config:/config

  default-worker:
    volumes:
      - data:/data
      - /opt/cilantro/config:/config

  convert-worker:
    volumes:
      - data:/data
      - /opt/cilantro/config:/config

  nlp-worker:
    volumes:
      - data:/data
      - /opt/cilantro/config:/config

  test:
    volumes:
      - data:/data
      - /opt/cilantro/config:/config

  ojs:
    volumes:
      - data:/data

  salvia:
    environment:
      BACKEND_URI: "http://oneeyedjacks01.dai-cloud.uni-koeln.de:5000"
      ZENON_URI: "https://zenon.dainst.org/api/v1"
      OJS_URI: "https://publications.dainst.org/journals/plugins/generic/ojs-cilantro-plugin/api"

volumes:
  redis-data:
  data:
