version: '3.5'

x-env-dirs: &env-dirs
  REPOSITORY_DIR: /data/repository
  WORKING_DIR: /data/workspace
  STAGING_DIR: /data/staging
  CONFIG_DIR: /config

x-env-broker: &env-broker
  BROKER_HOST: "broker"
  BROKER_USER: &broker-user user
  BROKER_PASSWORD: &broker-password password

services:

  broker:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: *broker-user
      RABBITMQ_DEFAULT_PASS: *broker-password
    ports:
      - "5672:5672"

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  service:
    image: dainst/cilantro-service:production-setup-2
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  default-worker:
    user: ${UID}
    image: dainst/cilantro-default-worker:production-setup
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  convert-worker:
    user: ${UID}
    image: dainst/cilantro-convert-worker:production-setup
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  nlp-worker:
    user: ${UID}
    image: dainst/cilantro-nlp-worker:production-setup
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  test:
    user: ${UID}
    image: dainst/cilantro-test:production-setup
    working_dir: /app
    tty: true
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"
      RESOURCE_DIR: "test/resources"

  monitor:
    image: dainst/cilantro-monitor:stable
    ports:
      - "5555:5555"
    environment:
      <<: *env-broker

  ojs:
    image: dainst/cilantro-ojs2:latest
    ports:
      - "4444:80"
