version: '3.5'

x-env-dirs: &env-dirs
  REPOSITORY_DIR: /data/repository
  WORKING_DIR: /data/workspace
  STAGING_DIR: /data/staging
  CONFIG_DIR: /config

x-test-timeouts: &test-timeouts
  DEFAULT_TEST_TIMEOUT: ${DEFAULT_TEST_TIMEOUT}
  JOURNAL_TEST_TIMEOUT: ${JOURNAL_TEST_TIMEOUT}

x-env-ojs: &env-ojs
  OJS_SERVER: ${OJS_SERVER}
  OJS_PORT: ${OJS_PORT}
  OJS_PATH: ${OJS_PATH}
  OJS_AUTH_KEY: ${OJS_AUTH_KEY}

x-env-broker: &env-broker
  BROKER_HOST: "broker"
  BROKER_USER: &broker-user user
  BROKER_PASSWORD: &broker-password password

x-env-jobdb: &env-jobdb
  JOB_DB_URL: ${JOB_DB_URL}
  JOB_DB_PORT: ${JOB_DB_PORT}
  JOB_DB_NAME: ${JOB_DB_NAME}


services:

  broker:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: *broker-user
      RABBITMQ_DEFAULT_PASS: *broker-password
    ports:
      - "5672:5672"

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  job-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data

  service:
    image: dainst/cilantro-service:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-service/Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-jobdb
      DB_HOST: "db"
      CILANTRO_ENV: development

  default-worker:
    user: ${UID}
    image: dainst/cilantro-default-worker:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-default-worker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-ojs
      <<: *env-jobdb
      DB_HOST: "db"
      CILANTRO_ENV: development

  convert-worker:
    user: ${UID}
    image: dainst/cilantro-convert-worker:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-convert-worker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"
      CILANTRO_ENV: development

  nlp-worker:
    user: ${UID}
    image: dainst/cilantro-nlp-worker:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-nlp-worker/Dockerfile
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"
      CILANTRO_ENV: development

  test:
    user: ${UID}
    image: dainst/cilantro-test:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-test/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    tty: true
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-ojs
      <<: *test-timeouts
      <<: *env-jobdb
      DB_HOST: "db"
      TEST_RESOURCE_DIR: "test/resources"

  monitor:
    image: dainst/cilantro-monitor:latest
    ports:
      - "5555:5555"
    environment:
      <<: *env-broker

  ojs:
    image: dainst/cilantro-ojs2:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-ojs2/Dockerfile
    volumes:
      - ./test/resources:/test/resources
      - ./data:/data
    ports:
      - "4444:80"

  salvia:
    image: dainst/cilantro-salvia:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-salvia/Dockerfile
    volumes:
        - ./frontend/img:/usr/share/nginx/html/img
        - ./frontend/info:/usr/share/nginx/html/info
        - ./frontend/js:/usr/share/nginx/html/js
        - ./frontend/partials:/usr/share/nginx/html/partials
        - ./frontend/style:/usr/share/nginx/html/style
        - ./frontend/test:/usr/share/nginx/html/test
    ports:
      - "7777:80"
    environment:
      BACKEND_URI: ${BACKEND_URI}
      ZENON_URI: ${ZENON_URI}
      OJS_URI: ${OJS_URI}

  frontend-test:
    tty: true
    image: dainst/cilantro-frontend-test:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-frontend-test/Dockerfile
    volumes:
      - ./frontend/img:/salvia/img
      - ./frontend/info:/salvia/info
      - ./frontend/js:/salvia/js
      - ./frontend/partials:/salvia/partials
      - ./frontend/style:/salvia/style
      - ./frontend/test:/salvia/test
    environment:
      TEST: ${TEST}
      BACKEND_URI: ${BACKEND_URI_TEST}
      ZENON_URI: ${ZENON_URI_TEST}
      OJS_URI: ${OJS_URI_TEST}
