version: '3.5'

services:

  db:
    volumes:
      - ./redis-data:/data

  job-db:
    volumes:
      - ./mongo-data:/data

  service:
    build:
      context: .
      dockerfile: ./docker/cilantro-service/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  default-worker:
    build:
      context: .
      dockerfile: ./docker/cilantro-default-worker/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  convert-worker:
    build:
      context: .
      dockerfile: ./docker/cilantro-convert-worker/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  nlp-worker:
    build:
      context: .
      dockerfile: ./docker/cilantro-nlp-worker/Dockerfile
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  test:
    build:
      context: .
      dockerfile: ./docker/cilantro-test/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config

  ojs:
    build:
      context: .
      dockerfile: ./docker/cilantro-ojs2/Dockerfile
    volumes:
      - ./test/resources:/test/resources
      - ./data:/data

  salvia:
    build:
      context: .
      dockerfile: ./docker/cilantro-salvia/Dockerfile
    volumes:
        - ./frontend/img:/usr/share/nginx/html/img
        - ./frontend/info:/usr/share/nginx/html/info
        - ./frontend/js:/usr/share/nginx/html/js
        - ./frontend/partials:/usr/share/nginx/html/partials
        - ./frontend/style:/usr/share/nginx/html/style
        - ./frontend/test:/usr/share/nginx/html/test

  frontend-test:
    build:
      context: .
      dockerfile: ./docker/cilantro-frontend-test/Dockerfile
    environment:
      TEST: ${TEST}
      BACKEND_URI: "http://service:5000"
      ZENON_URI: "https://zenon.dainst.org/api/v1"
      OJS_URI: "http://ojs:80/ojs/plugins/generic/ojs-cilantro-plugin/api"
    volumes:
      - ./frontend/img:/salvia/img
      - ./frontend/info:/salvia/info
      - ./frontend/js:/salvia/js
      - ./frontend/partials:/salvia/partials
      - ./frontend/style:/salvia/style
      - ./frontend/test:/salvia/test

