version: '3.5'

x-env-dirs: &env-dirs
  REPOSITORY_DIR: /data/repository
  WORKING_DIR: /data/workspace
  STAGING_DIR: /data/staging
  CONFIG_DIR: /config

x-env-ojs3: &env-ojs3
  MYSQL_USER: ${OJS3_MYSQL_USER}
  MYSQL_PASSWORD: ${OJS3_MYSQL_PASSWORD}
  ADMIN_USER: ${OJS3_ADMIN_USER}
  ADMIN_PASSWORD: ${OJS3_ADMIN_PASSWORD}

x-env-broker: &env-broker
  BROKER_HOST: "broker"
  BROKER_USER: &broker-user user
  BROKER_PASSWORD: &broker-password password

x-env-jobdb: &env-jobdb
  JOB_DB_URL: ${JOB_DB_URL}
  JOB_DB_PORT: ${JOB_DB_PORT}
  JOB_DB_NAME: ${JOB_DB_NAME}

x-env-app-config: &env-app-config
  OLD_JOBS_THRESHOLD_DAYS: ${OLD_JOBS_THRESHOLD_DAYS}

x-env-arachne: &env-arachne
  ARACHNE_DB_HOST: ${ARACHNE_DB_HOST}
  ARACHNE_DB_NAME: ${ARACHNE_DB_NAME}
  ARACHNE_DB_USER: ${ARACHNE_DB_USER}
  ARACHNE_DB_PASSWORD: ${ARACHNE_DB_PASSWORD}

x-env-archaeocloud: &env-archaeocloud
  ARCHAEOCLOUD_DIR: ${ARCHAEOCLOUD_DIR}
  BOOKSCAN_DIR: ${BOOKSCAN_DIR}
  PDF_DIR: ${PDF_DIR}
  METS_DIR: ${METS_DIR}
  TEI_DIR: ${TEI_DIR}
  PTIF_DIR: ${PTIF_DIR}
  ARCHIVE_DIR: ${ARCHIVE_DIR}

x-test-timeouts: &test-timeouts
  DEFAULT_TEST_TIMEOUT: ${DEFAULT_TEST_TIMEOUT}
  JOURNAL_TEST_TIMEOUT: ${JOURNAL_TEST_TIMEOUT}

services:

  broker:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: *broker-user
      RABBITMQ_DEFAULT_PASS: *broker-password
    ports:
      - "5672:5672"

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  job-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data

  service:
    image: dainst/cilantro-service:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-service/Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-jobdb
      <<: *env-app-config
      DB_HOST: "db"
      CILANTRO_ENV: development

  default-worker:
    image: dainst/cilantro-default-worker:latest
    user: ${UID}
    build:
      context: .
      dockerfile: ./docker/cilantro-default-worker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
      - ./archaeocloud_test_dir:/archaeocloud_test_dir
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-ojs3
      <<: *env-jobdb
      <<: *env-arachne
      <<: *env-archaeocloud
      DB_HOST: "db"
      CILANTRO_ENV: development
      BACKEND_URI: ${BACKEND_URI}

  convert-worker:
    image: dainst/cilantro-convert-worker:latest
    user: ${UID}
    build:
      context: .
      dockerfile: ./docker/cilantro-convert-worker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"
      CILANTRO_ENV: development

  nlp-worker:
    image: dainst/cilantro-nlp-worker:latest
    user: ${UID}
    build:
      context: .
      dockerfile: ./docker/cilantro-nlp-worker/Dockerfile
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"
      CILANTRO_ENV: development

  monitor:
    image: dainst/cilantro-monitor:latest
    build:
      context: .
      dockerfile: ./docker/cilantro-test/Dockerfile
    ports:
      - "5555:5555"
    environment:
      <<: *env-broker

  ojs3:
    image: dainst/cilantro-ojs3:latest
    ports:
      - "4444:8000"
    environment:
      <<: *env-ojs3
    build:
      context: .
      dockerfile: ./docker/cilantro-ojs3/Dockerfile
      args:
        <<: *env-ojs3

  test:
    container_name: cilantro_test
    user: ${UID}
    build:
      context: .
      dockerfile: ./docker/cilantro-test/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    tty: true
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-ojs3
      <<: *test-timeouts
      <<: *env-jobdb
      <<: *env-app-config
      <<: *env-arachne
      <<: *env-archaeocloud
      DB_HOST: "db"
      TEST_RESOURCE_DIR: "test/resources"
      BACKEND_URI: ${BACKEND_URI}

  arachne-db:
    image: mysql:5.5.62
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=arachne
    volumes:
      - ./test/resources/files/arachne.sql:/docker-entrypoint-initdb.d/arachne.sql
