version: '3.5'

x-env-dirs: &env-dirs
  REPOSITORY_DIR: /data/repository
  WORKING_DIR: /data/workspace
  STAGING_DIR: /data/staging
  CONFIG_DIR: /config

x-test-timeouts: &test-timeouts
  DEFAULT_TEST_TIMEOUT: ${DEFAULT_TEST_TIMEOUT}
  JOURNAL_TEST_TIMEOUT: ${JOURNAL_TEST_TIMEOUT}

x-env-ojs: &env-ojs
  OJS_SERVER: ${OJS_SERVER}
  OJS_PORT: ${OJS_PORT}
  OJS_AUTH_KEY: ${OJS_AUTH_KEY}

x-env-broker: &env-broker
  BROKER_HOST: "broker"
  BROKER_USER: &broker-user user
  BROKER_PASSWORD: &broker-password password

services:

  broker:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: *broker-user
      RABBITMQ_DEFAULT_PASS: *broker-password
    ports:
      - "5672:5672"

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  service:
    image: dainst/cilantro-service:latest
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  default-worker:
    user: ${UID}
    image: dainst/cilantro-default-worker:latest
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-ojs
      DB_HOST: "db"

  convert-worker:
    user: ${UID}
    image: dainst/cilantro-convert-worker:latest
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  nlp-worker:
    user: ${UID}
    image: dainst/cilantro-nlp-worker:latest
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  test:
    user: ${UID}
    image: dainst/cilantro-test:latest
    working_dir: /app
    tty: true
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-ojs
      <<: *test-timeouts
      DB_HOST: "db"
      RESOURCE_DIR: "test/resources"

  monitor:
    image: dainst/cilantro-monitor:latest
    ports:
      - "5555:5555"
    environment:
      <<: *env-broker

  ojs:
    image: dainst/cilantro-ojs2:latest
    ports:
      - "4444:80"

  salvia:
    image: dainst/cilantro-salvia:latest
    ports:
      - "7777:80"
    environment:
      BACKEND_URI: "http://localhost:5000"
      ZENON_URI: "https://zenon.dainst.org/api/v1"
      OJS_URI: "http://localhost:4444/ojs/plugins/generic/ojs-cilantro-plugin/api"

  frontend-test:
    image: dainst/cilantro-frontend-test:latest
