version: '3.5'

x-env-dirs: &env-dirs
  REPOSITORY_DIR: /data/repository
  WORKING_DIR: /data/workspace
  STAGING_DIR: /data/staging
  CONFIG_DIR: /config

x-env-ojs: &env-ojs
  OJS_SERVER: ${OJS_SERVER}
  OJS_PORT: ${OJS_PORT}
  OJS_PATH: ${OJS_PATH}
  OJS_AUTH_KEY: ${OJS_AUTH_KEY}

x-env-broker: &env-broker
  BROKER_HOST: "broker"
  BROKER_USER: &broker-user user
  BROKER_PASSWORD: &broker-password password

x-env-jobdb: &env-jobdb
  JOB_DB_URL: job-db
  JOB_DB_PORT: 27017
  JOB_DB_NAME: job_database

x-env-arachne: &env-arachne
  ARACHNE_DB_HOST: ${ARACHNE_DB_HOST}
  ARACHNE_DB_NAME: ${ARACHNE_DB_NAME}
  ARACHNE_DB_USER: ${ARACHNE_DB_USER}
  ARACHNE_DB_PASSWORD: ${ARACHNE_DB_PASSWORD}

services:

  broker:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: *broker-user
      RABBITMQ_DEFAULT_PASS: *broker-password

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  job-db:
    image: mongo
    volumes:
      - mongo-data:/data

  service:
    image: dainst/cilantro-service:latest
    volumes:
      - data:/data
      - /opt/cilantro/config:/config
    working_dir: /app
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-jobdb
      DB_HOST: "db"

  default-worker:
    user: ${UID}
    image: dainst/cilantro-default-worker:latest
    working_dir: /app
    volumes:
      - data:/data
      - /opt/cilantro/config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      <<: *env-ojs
      <<: *env-jobdb
      <<: *env-arachne
      DB_HOST: "db"

  convert-worker:
    user: ${UID}
    image: dainst/cilantro-convert-worker:latest
    working_dir: /app
    volumes:
      - data:/data
      - /opt/cilantro/config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  nlp-worker:
    user: ${UID}
    image: dainst/cilantro-nlp-worker:latest
    working_dir: /app
    volumes:
      - data:/data
      - /opt/cilantro/config:/config
    environment:
      <<: *env-dirs
      <<: *env-broker
      DB_HOST: "db"

  monitor:
    image: dainst/cilantro-monitor:stable
    environment:
      <<: *env-broker

  ojs:
    image: dainst/cilantro-ojs2:latest
    volumes:
      - data:/data

  salvia:
    image: dainst/cilantro-salvia:latest
    environment:
      <<: *env-ojs
      BACKEND_URI: ${BACKEND_URI}
      ZENON_URI: ${ZENON_URI}
      OJS_URI: ${OJS_URI}


volumes:
  mongo-data:
  redis-data:
  data:
    external:
      name: archaeocloud_data
