version: '3.5'

services:

  db:
    volumes:
      - ./redis-data:/data

  service:
    build:
      context: .
      dockerfile: ./docker/cilantro-service/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  default-worker:
    build:
      context: .
      dockerfile: ./docker/cilantro-default-worker/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  convert-worker:
    build:
      context: .
      dockerfile: ./docker/cilantro-convert-worker/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  nlp-worker:
    build:
      context: .
      dockerfile: ./docker/cilantro-nlp-worker/Dockerfile
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    environment:
      CILANTRO_ENV: development

  test:
    build:
      context: .
      dockerfile: ./docker/cilantro-test/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config

  ojs:
    build:
      context: .
      dockerfile: ./docker/cilantro-ojs2/Dockerfile
    volumes:
      - ./test/resources:/test/resources
      - ./data:/data

  salvia:
    build:
      context: .
      dockerfile: ./docker/cilantro-salvia/Dockerfile
    volumes:
      - ./frontend/img:/usr/share/nginx/html/img
      - ./frontend/info:/usr/share/nginx/html/info
      - ./frontend/js:/usr/share/nginx/html/js
      - ./frontend/partials:/usr/share/nginx/html/partials
      - ./frontend/style:/usr/share/nginx/html/style
      - ./frontend/test:/usr/share/nginx/html/test
      - ./frontend/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./frontend/gulpfile.js:/usr/share/nginx/html/gulpfile.js
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/package.json:/usr/share/nginx/html/package.json
      - ./frontend/package-lock.json:/usr/share/nginx/html/package-lock.json
      - ./frontend/version.json:/usr/share/nginx/html/version.json
      - node_modules:/usr/share/nginx/html/node_modules

  frontend-test:
    build:
      context: .
      dockerfile: ./docker/cilantro-frontend-test/Dockerfile
    volumes:
      - ./frontend/img:/salvia/img
      - ./frontend/info:/salvia/info
      - ./frontend/js:/salvia/js
      - ./frontend/partials:/salvia/partials
      - ./frontend/style:/salvia/style
      - ./frontend/test:/salvia/test
      - ./frontend/favicon.ico:/salvia/favicon.ico
      - ./frontend/gulpfile.js:/salvia/gulpfile.js
      - ./frontend/index.html:/salvia/index.html
      - ./frontend/package.json:/salvia/package.json
      - ./frontend/package-lock.json:/salvia/package-lock.json
      - ./frontend/version.json:/salvia/version.json
      - node_modules:/salvia/node_modules

volumes:
  node_modules: