version: '3.5'

services:

  task-broker:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    ports:
      - "5672:5672"

  task-db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  task-service:
    build:
      context: .
      dockerfile: docker/service/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "task-db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}

  task-worker:
    user: ${UID}
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "task-db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}

  task-nlp:
    user: ${UID}
    build:
      context: .
      dockerfile: docker/nlp/Dockerfile
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "task-db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}

  cilantro-test:
    user: ${UID}
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    tty: true
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "task-db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}
      RESOURCE_DIR: "test/resources"

  task-monitor:
    build:
      context: .
      dockerfile: docker/monitor/Dockerfile
    ports:
      - "5555:5555"
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
