version: '3.5'

services:

  broker:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    ports:
      - "5672:5672"

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  service:
    image: dainst/cilantro-service:multi-user
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    environment:
      BROKER_HOST: "broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}

  default-worker:
    user: ${UID}
    image: dainst/cilantro-default-worker:test_pdf
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    environment:
      BROKER_HOST: "broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}

  convert-worker:
    user: ${UID}
    image: dainst/cilantro-convert-worker:stable
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    environment:
      BROKER_HOST: "broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}

  nlp-worker:
    user: ${UID}
    image: dainst/cilantro-nlp-worker:stable
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    environment:
      BROKER_HOST: "broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}

  test:
    user: ${UID}
    image: dainst/cilantro-test:multi-user
    volumes:
      - .:/app
      - ./data:/data
      - ./config:/config
    working_dir: /app
    tty: true
    environment:
      BROKER_HOST: "broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}
      STAGING_DIR: ${STAGING_DIR}
      CONFIG_DIR: ${CONFIG_DIR}
      RESOURCE_DIR: "test/resources"

  monitor:
    image: dainst/cilantro-monitor:stable
    ports:
      - "5555:5555"
    environment:
      BROKER_HOST: "broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}

  ojs:
    image: dainst/cilantro-ojs2:1.0
    ports:
      - "4444:80"
    volumes:
      - ./test/resources:/test/resources
      - ./data:/data
