version: '3.5'

services:

  task-broker:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    ports:
      - "5672:5672"

  task-db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  task-service:
    build: ./service
    ports:
      - "5000:5000"
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "task-db"

  task-worker:
    build: ./workers
    volumes:
      - ./data:/app/data
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      DB_HOST: "task-db"
      REPOSITORY_DIR: ${REPOSITORY_DIR}
      WORKING_DIR: ${WORKING_DIR}

  task-monitor:
    build: ./monitor
    ports:
      - "5555:5555"
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
