FROM python:alpine

# needed for Pillow / PIL
RUN apk update
RUN apk add build-base jpeg-dev zlib-dev tiff-dev
ENV LIBRARY_PATH=/lib:/usr/lib

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

USER nobody

ENTRYPOINT watchmedo auto-restart -R -d worker -p="*.py" -- celery -A worker.tasks worker --loglevel=info
