FROM python:3

MAINTAINER Deutsches Archäologisches Institut "dev@dainst.de"

ENV REFRESHED_AT 2018-03-19
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get clean

RUN apt-get install -y \
      wget \
      unzip \
      default-jre \
      locales \
      python3 \
      python3-pip \
      git

RUN rm -rf /var/lib/apt/lists/*
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG LANG=en_US.UTF-8

# Install Treetagger for nlp_components
ENV TREETAGGER_ROOT /opt/bin/treetagger
ENV TREETAGGER_HOME $TREETAGGER_ROOT/cmd
ENV PATH $PATH:$TREETAGGER_ROOT/bin/:$TREETAGGER_ROOT/cmd/

RUN mkdir /opt/bin
RUN mkdir $TREETAGGER_ROOT
WORKDIR $TREETAGGER_ROOT

RUN wget http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-linux-3.2.1.tar.gz
RUN wget http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/tagger-scripts.tar.gz
RUN wget http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/german-par-linux-3.2-utf8.bin.gz
RUN wget http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/english-par-linux-3.2-utf8.bin.gz
RUN wget http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/italian-par-linux-3.2-utf8.bin.gz
RUN wget http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/spanish-par-linux-3.2-utf8.bin.gz
RUN wget http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/french-par-linux-3.2-utf8.bin.gz
RUN wget http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/install-tagger.sh
RUN sh install-tagger.sh

# Install Stanford NER  for nlp_components
ENV STANFORDHOME=/opt/bin/stanford_ner
ENV CLASSPATH=$CLASSPATH:$STANFORDHOME/stanford-ner.jar
ENV STANFORD_MODELS=$STANFORDHOME/models:$STANFORDHOME/classifiers
RUN mkdir $STANFORDHOME

WORKDIR /tmp
RUN wget https://nlp.stanford.edu/software/stanford-ner-2015-12-09.zip
RUN unzip stanford-ner-2015-12-09.zip
RUN mv stanford-ner-2015-12-09/* $STANFORDHOME
RUN rm stanford-ner-2015-12-09.zip

RUN wget http://nlp.dainst.org/html/nerclass/english.all.3class.distsim.crf.ser.gz -P $STANFORDHOME/classifiers
RUN wget http://nlp.dainst.org/html/nerclass/german.hgc_175m_600.crf.ser.gz -P $STANFORDHOME/classifiers
RUN wget http://nlp.dainst.org/html/nerclass/ner-ita-nogpe-noiob_gaz_wikipedia_sloppy.ser.gz -P $STANFORDHOME/classifiers
RUN wget http://nlp.dainst.org/html/nerclass/spanish.ancora.distsim.s512.crf.ser.gz -P $STANFORDHOME/classifiers

# Install Geoparser for nlp_components
## ATTENTION: The geoparser home folder is currently hardcoded in nlp_components
ENV GEOPARSER_HOME=/opt/nlp
RUN wget http://nlp.dainst.org/html/geo/geoparser-march2016.zip
RUN unzip geoparser-march2016.zip
RUN rm geoparser-march2016.zip
RUN mv geoparser-march2016 $GEOPARSER_HOME

# Python 3 dependencies for nlp_components
RUN pip3 install \
    NLTK \
    lxml \
    requests \
    langid \
    git+https://github.com/miotto/treetagger-python.git \
    pytest

RUN python3 -m nltk.downloader -d /usr/local/share/nltk_data punkt

ARG GITHUB_ACCESS_TOKEN
ENV PYLIB /usr/local/lib/python3.6/site-packages

RUN git clone https://x-access-token:${GITHUB_ACCESS_TOKEN}@github.com/dainst/nlp_components.git $PYLIB/nlp_components
RUN cp -R $PYLIB/nlp_components/idai_journals $PYLIB/idai_journals

ENV LIBRARY_PATH=/lib:/usr/lib
ENV PIPENV_VENV_IN_PROJECT=true
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN set -ex && mkdir /app
# workaround for pipenv bug: https://github.com/pypa/pipenv/issues/1328
WORKDIR /app
RUN cd $WORKDIR
COPY docker/Pipfile-nlp-worker Pipfile
COPY docker/Pipfile-nlp-worker.lock Pipfile.lock

RUN pip3 install pipenv
RUN set -ex && pipenv install --deploy --system

USER nobody

ENTRYPOINT watchmedo auto-restart -R -d nlp_worker -p="*.py" -- celery -Q nlp -A nlp_worker.tasks worker --loglevel=info
