FROM python:3

# needed for Pillow / PIL
RUN apt-get update
RUN apt-get -y install build-essential libjpeg-dev zlib1g-dev libtiff-dev pdftk

ENV LIBRARY_PATH=/lib:/usr/lib
ENV PIPENV_VENV_IN_PROJECT=true
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

WORKDIR /app

RUN pip install pipenv
RUN pipenv install
