about:
  title: Ingest a Journal-Issue to iDAI.publications/journals
  description: Create a new Issue of an existing journal, and upload it's files to iDAI.publications/journals
  tags: [OJS, iDAI.publications/journals, publish, journal, pdf]

tasks:
  - create_objects
  - split_pdf
  - foreach: "article_*"
    do:
      - if: do_ocr
        do:
          - convert_pdf_to_tiff
          - ocr_from_tiff
        else: extract_txt_from_pdf
      - generate_frontmatter
  - task: publish_to_ojs
    config: config/tasks/publish_to_ojs.yml
  - foreach: "article_*"
    do:
      - if: not do_ocr
        do: convert_pdf_to_tiff
      - foreach: "*.[tT][iI][fF]*"
        do: convert_tif_to_jpg
      - extract_entities
      - if: publish_to_webanno
        do: publish_to_webanno
      - task: convert_tsv_to_wadm
        config: config/tasks/convert_tsv_to_wadm.yml
  - cleanup_workdir
