tasks:
  - retrieve_from_staging
  - foreach: "\\.(tif|tiff|TIF|TIFF)$"
    do: convert.tif_to_jpg
  - foreach: "\\.(jpg|jpeg|JPG|JPEG)$"
    do: convert.jpg_to_pdf
  - convert.pdf_merge_converted
  - publish_to_repository
  - cleanup_workdir
