about:
  title: Ingest a Journal-Issue to iDAI.publications/journals
  description: Create a new Issue of an existing journal, and upload it's files to iDAI.publications/journals
  tags: [OJS, iDAI.publications/journals, publish, journal, pdf]

tasks:
  - create_object
  - list_parts:
    foreach:
    - if: do_ocr
      do:
      - list_files: origin
        pattern: ".*\\.pdf$"
        foreach:
          task: convert.pdf_to_tif
          target: tif
      - list_files: tif
        foreach:
          task: convert.tif_to_txt
          target: txt
      - list_files: tif
        foreach:
          task: convert.tif_to_jpg
          target: jpg
      else:
      - list_files: origin
        pattern: ".*\\.pdf$"
        foreach:
          task: convert.pdf_to_txt
          target: txt
    - task: nlp.annotate
      source: txt
  - list_parts:
    foreach:
      list_files: jpg
      foreach:
        task: convert.scale_image
        max_width: 50
        max_height: 50
        target_dir: thumbnails
  - list_parts:
    foreach:
      list_files: tif
      foreach:
        task: convert.scale_image
        max_width: 50
        max_height: 50
  - task: generate_xml
    template_file: ojs_template.xml
    target_filename: ojs_import.xml
    dtd_file: ojs_import.dtd
    params: ojs_metadata
  - list_parts:
    foreach:
        task: generate_xml
        template_file: marc_template.xml
        target_filename: marc.xml
        schema_file: MARC21slim.xsd
  - list_parts:
    foreach:
        task: generate_xml
        template_file: mets_template.xml
        target_filename: mets.xml
        schema_file: mets.xsd
  - task: generate_xml
    template_file: mets_template_journal.xml
    target_filename: mets.xml
    params: ojs_metadata
    schema_file: mets.xsd
  - task: publish_to_ojs
    params: ojs_metadata
  - list_parts:
    foreach:
      task: generate_frontmatter
  - publish_to_repository
  - cleanup_workdir
  - finish_job
