about:
  title: Ingest a Journal-Issue to iDAI.publications/journals
  description: Create a new Issue of an existing journal, and upload it's files to iDAI.publications/journals
  tags: OJS, iDAI.publications/journals, publish, journal, pdf

params:
  files_to_split: list
  paths: list
  metadata: dict

tasks:
  - retrieve_from_staging
  - write_metadata
  - convert_split_pdf
  - task: generate_marc_xml
    xml_template_path: resources/marc_template.xml
  - task: generate_xml
    xml_template_path: resources/ojs_template.xml
  - publish_to_repository
  - cleanup_workdir
