about:
  title: Ingest a complete book to iDAI.repository
  description: Create a new Book afrom single image files nd upload it to iDAI.repository
  tags: [repository, book, monography, image, tiff]

params:
  paths: list

tasks:
  - retrieve_from_staging
  - foreach: "\\.(tif|tiff|TIF|TIFF)$"
    do: convert.tif_to_jpg
  - foreach: "\\.(jpg|jpeg|JPG|JPEG)$"
    do: convert.jpg_to_pdf
  - convert.pdf_merge_converted
  - publish_to_repository
  - cleanup_workdir
