about:
  title: Ingest a complete book to iDAI.repository
  description: Create a new Book afrom single image files nd upload it to iDAI.repository
  tags: [repository, book, monography, image, tiff]

tasks:
  - task: create_object
    create_subobject: false
  - list_files: origin
    pattern: "\\.(tif|tiff|TIF|TIFF)$"
    foreach:
      - task: convert.tif_to_jpg
        target: jpg
      - task: convert.tif_to_ptif
        target: ptif
  - list_files: jpg
    foreach:
      task: convert.jpg_to_pdf
      target: pdf
  - list_files: jpg
    foreach:
      task: convert.scale_image
      max_width: 50
      max_height: 50
      target: jpg_thumbnails
  - task: convert.merge_converted_pdf
    representation: pdf
  - publish_to_arachne_db
  - task: generate_xml
    template_file: mets_template_book.xml
    target_filename: mets.xml
    schema_file: mets.xsd
  - task: generate_xml
    template_file: tei_template.xml
    target_filename: tei.xml
  - publish_to_cloud
  - publish_to_repository
  - cleanup_workdir
  - finish_job
