about:
  title: Ingest a complete book to iDAI.repository
  description: Create a new Book afrom single image files nd upload it to iDAI.repository
  tags: repository, book, monography, image, tiff

params:
  paths: list

tasks:
  - retrieve_from_staging
  - foreach: "\\.(tif|tiff|TIF|TIFF)$"
    do: convert_tif_to_jpg
  - foreach: "\\.(jpg|jpeg|JPG|JPEG)$"
    do: convert_jpg_to_pdf
  - convert_pdf_merge_converted
  - publish_to_repository
  - cleanup_workdir
