tasks:
  - retrieve_from_staging
  - foreach: "*.[tT][iI][fF]*"
    do: convert.tif_to_jpg
  - foreach: "*.[jJ][pP][gG]*"
    do: convert.jpg_to_pdf
  - convert.pdf_merge_converted
  - publish_to_repository
  - cleanup_workdir
