about:
  title: Ingest a complete book to iDAI.repository
  description: Create a new Book afrom single image files nd upload it to iDAI.repository
  tags: [repository, book, monography, image, tiff]

params:
  files: list
  metadata: dict

tasks:
  - create_object
  - foreach: "\\.(tif|tiff|TIF|TIFF)$"
    do: convert.tif_to_jpg
  - foreach: "\\.(jpg|jpeg|JPG|JPEG)$"
    do: convert.jpg_to_pdf
  - convert.merge_converted_pdf
  - publish_to_repository
  - cleanup_workdir
