params:
  files_to_split: list
  paths: list
  metadata: dict

tasks:
  - retrieve_from_staging
  - write_metadata
  - convert.split_pdf
  - task: generate_marc_xml
    xml_template_path: resources/marc_template.xml
  - task: generate_xml
    xml_template_path: resources/ojs_template.xml
  - publish_to_repository
  - cleanup_workdir
