about:
  title: Ingest a Journal-Issue to iDAI.publications/journals
  description: Create a new Issue of an existing journal, and upload it's files to iDAI.publications/journals
  tags: [OJS, iDAI.publications/journals, publish, journal, pdf]

params:
  files: list
  parts: list
  metadata: dict
  nlp_params: dict
  do_ocr: boolean
  frontmatter_ids: list
  ojs_metadata: dict

tasks:
  - create_object
  - list_parts:
    foreach:
    - if: do_ocr
      do:
      - list_files: origin
        pattern: ".*\\.pdf$"
        foreach:
          task: convert.pdf_to_tif
          target: tif
      - list_files: tif
        foreach:
          task: convert.tif_to_txt
          target: txt
      else:
      - list_files: origin
        pattern: ".*\\.pdf$"
        foreach:
          task: convert.pdf_to_txt
          target: txt
    - list_files: txt
      foreach: nlp.annotate
  - task: generate_xml
    xml_type: ojs
  - list_parts:
    foreach:
        task: generate_xml
        xml_type: marc
  - publish_to_ojs
  - generate_frontmatter
  - publish_to_repository
  - cleanup_workdir
