about:
  title: Ingest a complete book to iDAI.repository
  description: Create a new Book afrom single image files nd upload it to iDAI.repository
  tags: [repository, book, monography, image, tiff]

params:
  files: list
  metadata: dict

tasks:
  - create_object
  - foreach: origin
    pattern: "\\.(tif|tiff|TIF|TIFF)$"
    do:
      task: convert.tif_to_jpg
      target: jpg
  - foreach: jpg
    do:
      task: convert.jpg_to_pdf
      target: pdf
  - task: convert.merge_converted_pdf
    representation: pdf
  - publish_to_repository
  - cleanup_workdir
