about:
  title: Create Annotations
  description: Create Annotations for document
  tags: NLP, Information Retrieval, Data Mining, Annotations

params:
  paths: list

tasks:
  - retrieve_from_staging
  - nlp_annotate
  - cleanup_workdir
