about:
  title: Create Annotations
  description: Create Annotations for document
  tags: [NLP, Information Retrieval, Data Mining, Annotations]

params:
  paths: list

tasks:
  - retrieve_from_staging
  - nlp.annotate
  - publish_to_repository
  - cleanup_workdir
